# chart-repo: argo/argo
# chart-version: latest
# chart-ingress: true

ui:
  ingress:
    enabled: INGRESS_ENABLED
    hosts:
      - INGRESS_DOMAIN
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
      - secretName: argo-ui-tls
        hosts:
          - INGRESS_DOMAIN

useDefaultArtifactRepo: true
useStaticCredentials: false

artifactRepository:
  s3:
    bucket: AWS_BUCKET
    endpoint: s3.amazonaws.com
