# chart-repo: stable/jenkins
# chart-version: latest
# chart-ingress: true
# chart-pvc: jenkins ReadWriteOnce 8Gi

# nameOverride: jenkins

master:
  adminUser: admin
  adminPassword: PASSWORD
  resources:
    requests:
      cpu: 1000m
      memory: 3Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  # PodAnnotations:
  #   cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  hostNetworking: true
  javaOpts: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Seoul"
  serviceType: SERVICE_TYPE
  ingress:
    enabled: INGRESS_ENABLED
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      # external-dns.alpha.kubernetes.io/hostname: "INGRESS_DOMAIN."
    hostName: INGRESS_DOMAIN
    tls:
      - secretName: jenkins-tls
        hosts:
          - INGRESS_DOMAIN
  overwritePlugins: true
  installPlugins:
    # https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml
    - kubernetes:latest
    - workflow-job:latest
    - workflow-aggregator:latest
    - credentials-binding:latest
    # https://plugins.jenkins.io/blueocean
    - blueocean:latest
    # https://plugins.jenkins.io/kubernetes-credentials-provider
    - kubernetes-credentials-provider:latest
    # https://plugins.jenkins.io/pipeline-github-lib
    - pipeline-github-lib:latest
    # https://plugins.jenkins.io/active-directory
    - active-directory:latest
    # https://plugins.jenkins.io/role-strategy
    - role-strategy:latest
    # https://plugins.jenkins.io/ldap
    - ldap:latest
    # https://plugins.jenkins.io/google-login
    - google-login:latest
  prometheus:
    enabled: false
  overwriteJobs: true
  # -- jenkins-jobs -- start -- see: jenkins/jobs.sh #
  # -- jenkins-jobs -- end -- #

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  #:EFS:storageClass: "efs"
  existingClaim: jenkins
