# chart-repo: stable/nginx-ingress
# chart-version: latest

nameOverride: nginx-ingress-tcp

controller:
  kind: DaemonSet
  config:
    use-forwarded-headers: "true"
  service:
    annotations:
      # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ""
      # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
      # external-dns.alpha.kubernetes.io/hostname: "demo.domain.com."
      # external-dns.alpha.kubernetes.io/ttl: 300
    clusterIP: "SERVICE_CLUSTER_IP"
  stats:
    enabled: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      clusterIP: "METRICS_CLUSTER_IP"

defaultBackend:
  service:
    clusterIP: "BACKEND_CLUSTER_IP"
