# chart-repo: stable/nginx-ingress
# chart-version: latest

nameOverride: nginx-ingress

controller:
  kind: DaemonSet
  config:
    use-forwarded-headers: "true"
  stats:
    enabled: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
    serviceMonitor:
      enabled: true
