# chart-repo: stable/kube2iam
# chart-version: latest

nameOverride: kube2iam

aws:
  region: AWS_REGION
#:AWS:  access_key: AWS_ACCESS_KEY
#:AWS:  secret_key: AWS_SECRET_KEY

# extraArgs:
#   base-role-arn: BASE_ROLE_ARN
#   default-role: DEFAULT_ROLE

# host:
#   iptables: true
#   interface: cbr0

rbac:
  create: true
