apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo-ui
  namespace: argo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: argo-ui.sample.opsnow.io
    http:
      paths:
      - path: /
        backend:
          serviceName: argo-ui
          servicePort: 80
