# ------------------- Ingress ------------------- #

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: istio-igw
  namespace: NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: istio-igw-NAMESPACE.BASE_DOMAIN
    http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: http
  tls:
  - hosts:
    - istio-igw-NAMESPACE.BASE_DOMAIN
    secretName: istio-igw-tls
