# chart-repo: istio
# chart-version: latest

global:
  k8sIngress:
    enabled: true
    enableHttps: true
    gatewayName: ingressgateway

grafana:
  enabled: true

tracing:
  enabled: true

kiali:
  enabled: true
  createDemoSecret: true

gateways:
  istio-ingressgateway:
    sds:
      enabled: true

  # istio-egressgateway:
  #   enabled: true
