# chart-repo: istio
# chart-version: latest

global:
  k8sIngress:
    enabled: true
    enableHttps: true
    gatewayName: ingressgateway

gateways:
  istio-ingressgateway:
    enabled: true
    # sds:
    #   enabled: true

  istio-egressgateway:
    enabled: true

# certmanager:
#   enabled: true
#   email: me@nalbam.com

grafana:
  enabled: true

tracing:
  enabled: true

kiali:
  enabled: true
  createDemoSecret: true
