# chart-repo: istio
# chart-version: latest

global:
  k8sIngress:
    enabled: true
    enableHttps: true
    gatewayName: ingressgateway

gateways:
  istio-ingressgateway:
    enabled: true
    sds:
      enabled: true

  istio-egressgateway:
    enabled: true

grafana:
  enabled: true

tracing:
  enabled: true

kiali:
  enabled: true
  createDemoSecret: true
