apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app: letsencrypt-prod
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@nalbam.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}

---

apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app: letsencrypt-staging
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: me@nalbam.com
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
