apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
  - default:
      cpu: 600m
      memory: 1252Mi
    defaultRequest:
      cpu: 500m
      memory: 1024Mi
    min:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: 1000m
      memory: 2048Mi
    type: Container
